services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: nexgo
      POSTGRES_USER: nexgo
      POSTGRES_PASSWORD: nexgo_local_only
    ports:
      - '${NEXGO_PG_PORT:-5432}:5432'
    volumes:
      - nexgo-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nexgo -d nexgo']
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - nexgo-redis:/data

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ':9001'
    environment:
      MINIO_ROOT_USER: nexgo_local
      MINIO_ROOT_PASSWORD: nexgo_local_only_change_me
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - nexgo-minio:/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  nexgo-postgres:
  nexgo-redis:
  nexgo-minio:
