'use client';

import { useCallback, useEffect, useState } from 'react';
import { apiFetch, ApiError } from '@/lib/api';
import { useAppState } from '@/lib/AppStateContext';
import * as T from '@/lib/theme';

const CARD = { background: 'linear-gradient(165deg,var(--nx-glass-1),var(--nx-glass-2))', border: '1px solid var(--nx-glass-border)', borderRadius: 14, boxShadow: '0 12px 30px rgba(15,31,61,.07)' };
const field = { width: '100%', height: 40, boxSizing: 'border-box', borderRadius: 8, border: `1px solid ${T.INPUT_BORDER}`, background: T.SURFACE, color: T.TEXT, padding: '0 11px', outline: 'none', fontSize: 13 };
const money = (v = 0) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Number(v) / 100);
const title = (v = '') => v.replaceAll('_', ' ').replace(/\b\w/g, (c) => c.toUpperCase());

function Button({ children, onClick, disabled, primary = false }) { return <button disabled={disabled} onClick={onClick} style={{ height: 34, padding: '0 11px', borderRadius: 8, border: `1px solid ${primary ? T.NAVY : T.INPUT_BORDER}`, background: primary ? T.NAVY : T.SURFACE, color: primary ? '#fff' : T.TEXT, fontWeight: 720, fontSize: 12, cursor: disabled ? 'wait' : 'pointer', opacity: disabled ? .6 : 1 }}>{children}</button>; }
function State({ children }) { return <span style={{ display: 'inline-flex', padding: '4px 8px', borderRadius: 99, color: T.GREEN, background: `${T.GREEN}14`, fontSize: 11.5, fontWeight: 720 }}>{children}</span>; }
function Shell({ title, intro, children, mobile }) { return <div style={{ padding: mobile ? '14px 12px 42px' : '18px 22px 48px', maxWidth: 1120 }}><div style={{ margin: '0 0 15px' }}><div style={{ color: T.TEXT, fontSize: 19, fontWeight: 760 }}>{title}</div><div style={{ marginTop: 4, color: T.TEXT_SECONDARY, fontSize: 13 }}>{intro}</div></div>{children}</div>; }
function Notice({ children, error }) { return <div style={{ ...CARD, padding: 18, color: error ? T.RED : T.TEXT_SECONDARY, fontSize: 13 }}>{children}</div>; }
function Rows({ rows, columns, mobile }) { if (!rows.length) return <Notice>No records yet. Create one here and it will persist in your workspace.</Notice>; return <div style={{ ...CARD, overflow: 'hidden' }}><div style={{ overflowX: 'auto' }}><table style={{ width: '100%', minWidth: mobile ? 560 : 720, borderCollapse: 'collapse' }}><thead><tr>{columns.map(c => <th key={c.label} style={{ padding: '11px 14px', textAlign: 'left', fontSize: 10.5, letterSpacing: '.07em', color: T.TEXT_MUTED, background: T.TABLE_HEAD, textTransform: 'uppercase' }}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r, ri) => <tr key={r.id || ri}>{columns.map((c, i) => <td key={i} style={{ padding: '13px 14px', borderTop: `1px solid ${T.DIVIDER}`, color: T.TEXT_LABEL, fontSize: 13 }}>{c.render(r)}</td>)}</tr>)}</tbody></table></div></div>; }

function Channels({ provider, mobile }) { const { showToast } = useAppState(); const [items, setItems] = useState([]); const [name, setName] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(() => apiFetch('/v1/channels').then(x => setItems(x.items || [])).catch(() => setItems([])), []); useEffect(() => { load(); }, [load]);
  const add = async () => { if (!name.trim()) return; setBusy(true); try { await apiFetch('/v1/channels', { method: 'POST', body: { provider, displayName: name.trim() } }); setName(''); showToast(`${title(provider)} connection saved`); load(); } catch (e) { showToast(e.message || 'Connection could not be created', 'error'); } finally { setBusy(false); } };
  const sync = async (id) => { try { await apiFetch(`/v1/channels/${id}/sync`, { method: 'POST' }); showToast('Sync job queued. It will appear in Jobs shortly.'); load(); } catch (e) { showToast(e.message || 'Unable to queue sync', 'error'); } };
  const matching = items.filter(x => x.provider === provider); return <Shell title={`${title(provider)} integration`} intro="Save a connection and queue a live sync job. Credentials are deliberately connected later through the secure provider hand-off." mobile={mobile}><div style={{ ...CARD, padding: 16, display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 14 }}><input value={name} onChange={e => setName(e.target.value)} placeholder={`${title(provider)} store name`} style={{ ...field, flex: '1 1 240px' }} /><Button primary disabled={busy || !name.trim()} onClick={add}>Connect channel</Button></div><Rows mobile={mobile} rows={matching} columns={[{ label: 'Connection', render: r => <><b>{r.display_name}</b><small style={{ display: 'block', color: T.TEXT_MUTED, marginTop: 3 }}>{title(r.provider)}</small></> }, { label: 'Status', render: r => <State>{title(r.state)}</State> }, { label: 'Last sync', render: r => r.last_synced_at ? new Date(r.last_synced_at).toLocaleString('en-IN') : 'Not synced yet' }, { label: '', render: r => <Button onClick={() => sync(r.id)}>Sync orders</Button> }]} /></Shell>; }

function Recharge({ mobile }) { const { showToast } = useAppState(); const [amount, setAmount] = useState('1000'); const [items, setItems] = useState([]); const [busy, setBusy] = useState(false); const load = useCallback(() => apiFetch('/v1/wallet/recharges').then(x => setItems(x.items || [])), []); useEffect(() => { load(); }, [load]); const create = async () => { setBusy(true); try { const x = await apiFetch('/v1/wallet/recharge', { method: 'POST', body: { amountPaise: Math.round(Number(amount) * 100) } }); showToast(`Recharge request ${x.providerOrderId} created. Payment confirmation is handled by Razorpay.`); load(); } catch (e) { showToast(e.message || 'Enter an amount of at least ₹100', 'error'); } finally { setBusy(false); } }; return <Shell title="Wallet recharge" intro="Create a Razorpay recharge request. The wallet is credited only after a verified payment webhook." mobile={mobile}><div style={{ ...CARD, padding: 16, display: 'flex', gap: 10, alignItems: 'end', flexWrap: 'wrap', marginBottom: 14 }}><label style={{ color: T.TEXT_LABEL, fontSize: 12.5, fontWeight: 650, flex: '1 1 190px' }}>Amount (₹)<input min="100" type="number" value={amount} onChange={e => setAmount(e.target.value)} style={{ ...field, marginTop: 6 }} /></label><Button primary disabled={busy} onClick={create}>{busy ? 'Creating…' : 'Create payment request'}</Button></div><Rows mobile={mobile} rows={items} columns={[{ label: 'Reference', render: r => <b style={{ fontFamily: T.MONO }}>{r.provider_order_id}</b> }, { label: 'Amount', render: r => money(r.amount_paise) }, { label: 'Status', render: r => <State>{title(r.status)}</State> }, { label: 'Created', render: r => new Date(r.created_at).toLocaleString('en-IN') }]} /></Shell>; }

function Warehouse({ mobile }) { const { showToast } = useAppState(); const blank = { name: '', contactName: '', fullName: '', phone: '', email: '', addressLine1: '', city: '', state: '', pincode: '' }; const [f, setF] = useState(blank); const [items, setItems] = useState([]); const [busy, setBusy] = useState(false); const load = useCallback(() => apiFetch('/v1/warehouses').then(x => setItems(x.items || [])), []); useEffect(() => { load(); }, [load]); const submit = async e => { e.preventDefault(); setBusy(true); try { await apiFetch('/v1/warehouses', { method: 'POST', body: f }); setF(blank); showToast('Warehouse added to your shipping workspace'); load(); } catch (x) { showToast(x.message || 'Check the warehouse details', 'error'); } finally { setBusy(false); } }; return <Shell title="Warehouse settings" intro="Add dispatch locations used when creating and booking orders." mobile={mobile}><form onSubmit={submit} style={{ ...CARD, padding: 16, marginBottom: 14 }}><div style={{ display: 'grid', gridTemplateColumns: mobile ? '1fr' : 'repeat(3,1fr)', gap: 10 }}>{Object.entries(f).map(([k, v]) => <label key={k} style={{ color: T.TEXT_LABEL, fontSize: 12, fontWeight: 650 }}>{title(k)}<input required={k !== 'email'} value={v} onChange={e => setF({ ...f, [k]: e.target.value })} style={{ ...field, marginTop: 5 }} /></label>)}</div><div style={{ marginTop: 13 }}><Button primary disabled={busy}>{busy ? 'Saving…' : 'Add warehouse'}</Button></div></form><Rows mobile={mobile} rows={items} columns={[{ label: 'Warehouse', render: r => <><b>{r.name}</b><small style={{ display: 'block', color: T.TEXT_MUTED, marginTop: 3 }}>{r.contact_name}</small></> }, { label: 'Location', render: r => `${r.city}, ${r.state} · ${r.pincode}` }, { label: 'Status', render: r => <State>{r.is_active ? 'Active' : 'Inactive'}</State> }]} /></Shell>; }

function Team({ mobile }) { const { showToast } = useAppState(); const [data, setData] = useState(null); const [email, setEmail] = useState(''); const [role, setRole] = useState('operations'); const load = useCallback(() => apiFetch('/v1/seller/team').then(setData), []); useEffect(() => { load(); }, [load]); const invite = async () => { try { await apiFetch('/v1/seller/team/invite', { method: 'POST', body: { email, role } }); setEmail(''); showToast('Invitation created and email queued'); load(); } catch (e) { showToast(e.message || 'Invite could not be created', 'error'); } }; return <Shell title="Team and roles" intro="Control who can work in the seller workspace. Owner permissions are enforced by the backend." mobile={mobile}><div style={{ ...CARD, padding: 16, display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 14 }}><input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="teammate@company.com" style={{ ...field, flex: '1 1 240px' }} /><select value={role} onChange={e => setRole(e.target.value)} style={{ ...field, width: 150 }}><option value="operations">Operations</option><option value="finance">Finance</option><option value="read_only">Read only</option></select><Button primary disabled={!email} onClick={invite}>Invite teammate</Button></div><Rows mobile={mobile} rows={data?.members || []} columns={[{ label: 'Member', render: r => <><b>{r.full_name}</b><small style={{ display: 'block', color: T.TEXT_MUTED, marginTop: 3 }}>{r.email}</small></> }, { label: 'Role', render: r => <State>{title(r.role)}</State> }, { label: 'Joined', render: r => new Date(r.created_at).toLocaleDateString('en-IN') }]} />{data?.pendingInvitations?.length > 0 && <div style={{ marginTop: 14, ...CARD, padding: 14, color: T.TEXT_SECONDARY, fontSize: 13 }}>{data.pendingInvitations.length} pending invitation{data.pendingInvitations.length > 1 ? 's' : ''} waiting to be accepted.</div>}</Shell>; }

function Kyc({ mobile }) { const { showToast } = useAppState(); const [current, setCurrent] = useState(null); const [f, setF] = useState({ gstin: '', pan: '', entityType: 'proprietorship', registeredAddress: '', bankAccountHolder: '', bankAccountNumber: '', bankIfsc: '' }); const [busy, setBusy] = useState(false); const load = useCallback(() => apiFetch('/v1/seller/kyc').then(setCurrent), []); useEffect(() => { load(); }, [load]); const submit = async e => { e.preventDefault(); setBusy(true); try { await apiFetch('/v1/seller/kyc', { method: 'POST', body: f }); showToast('KYC submitted for platform review'); load(); } catch (x) { showToast(x.message || 'Check the KYC information', 'error'); } finally { setBusy(false); } }; if (current && current.status !== 'unsubmitted' && current.status !== 'rejected') return <Shell title="KYC verification" intro="Your business identity and settlement details." mobile={mobile}><Notice>Your KYC is currently <b>{title(current.status)}</b>{current.rejection_reason ? `: ${current.rejection_reason}` : ''}. Bank account data remains protected on the server.</Notice></Shell>; return <Shell title="KYC verification" intro="Submit business and settlement information for secure platform approval." mobile={mobile}><form onSubmit={submit} style={{ ...CARD, padding: 16 }}><div style={{ display: 'grid', gridTemplateColumns: mobile ? '1fr' : '1fr 1fr', gap: 10 }}>{Object.entries(f).map(([k, v]) => <label key={k} style={{ color: T.TEXT_LABEL, fontSize: 12, fontWeight: 650 }}>{title(k)}{k === 'entityType' ? <select value={v} onChange={e => setF({ ...f, [k]: e.target.value })} style={{ ...field, marginTop: 5 }}><option value="proprietorship">Proprietorship</option><option value="partnership">Partnership</option><option value="private_limited">Private limited</option><option value="llp">LLP</option><option value="public_limited">Public limited</option></select> : <input value={v} onChange={e => setF({ ...f, [k]: e.target.value })} style={{ ...field, marginTop: 5 }} />}</label>)}</div><div style={{ marginTop: 13 }}><Button primary disabled={busy}>{busy ? 'Submitting…' : 'Submit for review'}</Button></div></form></Shell>; }

function FinanceList({ kind, mobile }) { const path = kind === 'invoice' ? '/v1/seller/invoices' : '/v1/seller/cod-remittances'; const [items, setItems] = useState([]); useEffect(() => { apiFetch(path).then(x => setItems(x.items || [])).catch(() => setItems([])); }, [path]); const invoice = kind === 'invoice'; return <Shell title={invoice ? 'Shipping invoices' : 'COD remittances'} intro={invoice ? 'Issued invoices and billing periods generated by platform finance.' : 'COD collections cleared through your platform remittance cycles.'} mobile={mobile}><Rows mobile={mobile} rows={items} columns={invoice ? [{ label: 'Invoice', render: r => <b>{r.invoice_number}</b> }, { label: 'Period', render: r => `${r.period_start} → ${r.period_end}` }, { label: 'Total', render: r => money(r.total_paise) }, { label: 'Status', render: r => <State>{title(r.status)}</State> }] : [{ label: 'Cycle', render: r => `${r.cycle_start} → ${r.cycle_end}` }, { label: 'Shipments', render: r => r.shipment_count }, { label: 'Net remittance', render: r => money(r.net_remitted_paise) }, { label: 'Status', render: r => <State>{title(r.status)}</State> }]} /></Shell>; }

function RateTool({ activeId, mobile }) { const [pincode, setPincode] = useState('560001'); const [weight, setWeight] = useState('500'); const [paymentMode, setPaymentMode] = useState('prepaid'); const [quotes, setQuotes] = useState([]); const [error, setError] = useState(''); const lookup = async () => { setError(''); try { const x = await apiFetch('/v1/shipping/quotes', { method: 'POST', body: { destinationPincode: pincode, weightG: Number(weight), paymentMode } }); setQuotes(x.quotes || []); } catch (e) { setQuotes([]); setError(e.message || 'No live courier options matched this destination.'); } }; const serviceability = activeId === 'pincode'; return <Shell title={serviceability ? 'Pincode serviceability' : activeId === 'ratecard' ? 'Your available rate card' : 'Rate calculator'} intro={serviceability ? 'Check live courier coverage and services for any delivery pincode.' : 'Compare the admin-configured courier prices that will be available at booking.'} mobile={mobile}><div style={{ ...CARD, padding: 16 }}><div style={{ display: 'grid', gridTemplateColumns: mobile ? '1fr' : '1.15fr .7fr .7fr auto', gap: 10, alignItems: 'end' }}><label style={{ color: T.TEXT_LABEL, fontSize: 12, fontWeight: 650 }}>Destination pincode<input value={pincode} maxLength={6} onChange={e => setPincode(e.target.value.replace(/\D/g, ''))} style={{ ...field, marginTop: 5 }} /></label><label style={{ color: T.TEXT_LABEL, fontSize: 12, fontWeight: 650 }}>Weight (g)<input value={weight} type="number" min="1" onChange={e => setWeight(e.target.value)} style={{ ...field, marginTop: 5 }} /></label><label style={{ color: T.TEXT_LABEL, fontSize: 12, fontWeight: 650 }}>Payment<select value={paymentMode} onChange={e => setPaymentMode(e.target.value)} style={{ ...field, marginTop: 5 }}><option value="prepaid">Prepaid</option><option value="cod">COD</option></select></label><Button primary onClick={lookup}>{serviceability ? 'Check coverage' : 'Calculate rates'}</Button></div>{error && <div style={{ marginTop: 12, color: T.RED, fontSize: 13 }}>{error}</div>}{quotes.length > 0 && <div style={{ display: 'grid', gridTemplateColumns: mobile ? '1fr' : 'repeat(3,minmax(0,1fr))', gap: 10, marginTop: 16 }}>{quotes.map((q, i) => <div key={`${q.provider.code}-${q.service.code}`} style={{ padding: 13, borderRadius: 10, border: `1px solid ${i === 0 ? T.ACCENT : T.BORDER}`, background: i === 0 ? 'rgba(0,179,164,.08)' : T.SURFACE }}><b style={{ color: T.TEXT, fontSize: 13 }}>{q.provider.name}</b><small style={{ display: 'block', color: T.TEXT_MUTED, marginTop: 3 }}>{q.service.name} · ETA {q.etaDays} days</small>{!serviceability && <strong style={{ display: 'block', color: T.TEXT, fontSize: 20, marginTop: 9 }}>₹{q.price.total.toFixed(2)}</strong>}<State>{serviceability ? 'Serviceable' : i === 0 ? 'Best configured rate' : 'Available'}</State></div>)}</div>}</div></Shell>; }

export default function LiveSellerWorkspace({ activeId, mobile }) { if (['shopify', 'woo', 'magento', 'amazon'].includes(activeId)) return <Channels provider={activeId === 'woo' ? 'woocommerce' : activeId === 'magento' ? 'custom' : activeId} mobile={mobile} />; if (activeId === 'recharges') return <Recharge mobile={mobile} />; if (activeId === 'warehouse') return <Warehouse mobile={mobile} />; if (activeId === 'profile') return <Team mobile={mobile} />; if (activeId === 'kyc') return <Kyc mobile={mobile} />; if (activeId === 'invoice' || activeId === 'cod') return <FinanceList kind={activeId} mobile={mobile} />; if (['ratecalc', 'ratecard', 'pincode'].includes(activeId)) return <RateTool activeId={activeId} mobile={mobile} />; return null; }
