'use client';

import { useCallback, useEffect, useState } from 'react';
import { apiFetch, ApiError } from '@/lib/api';
import { useAppState } from '@/lib/AppStateContext';
import * as T from '@/lib/theme';

const CARD = { background: 'var(--nx-surface)', border: '1px solid var(--nx-border)', borderRadius: 10, boxShadow: '0 1px 2px rgba(20,44,66,.04), 0 8px 24px rgba(20,44,66,.045)' };
function Button({ children, onClick, primary, disabled }) { return <button disabled={disabled} onClick={onClick} style={{ height: 35, padding: '0 11px', borderRadius: 8, border: `1px solid ${primary ? T.NAVY : T.INPUT_BORDER}`, background: primary ? T.NAVY : T.SURFACE, color: primary ? '#fff' : T.TEXT, fontSize: 12, fontWeight: 720, cursor: disabled ? 'wait' : 'pointer', opacity: disabled ? .58 : 1 }}>{children}</button>; }

export default function LiveSellerSecurity({ mobile }) {
  const { showToast } = useAppState(); const [me, setMe] = useState(null); const [sessions, setSessions] = useState([]); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const [profile, list] = await Promise.all([apiFetch('/v1/seller/me'), apiFetch('/v1/seller/sessions')]); setMe(profile); setSessions(list.items || []); } catch { setSessions([]); } }, []);
  useEffect(() => { load(); }, [load]); // eslint-disable-line react-hooks/set-state-in-effect -- async fetch on mount; state is set after the await
  const reset = async () => { if (!me?.email) return; setBusy(true); try { await apiFetch('/v1/auth/forgot-password', { method: 'POST', body: { email: me.email } }); showToast('Password reset instructions were queued to your sign-in email.'); } catch (error) { showToast(error instanceof ApiError ? error.message : 'Reset request could not be created', 'error'); } finally { setBusy(false); } };
  const revokeOthers = async () => { setBusy(true); try { const result = await apiFetch('/v1/seller/sessions/revoke-others', { method: 'POST' }); showToast(`${result.revokedCount || 0} other session${result.revokedCount === 1 ? '' : 's'} signed out.`); load(); } catch (error) { showToast(error instanceof ApiError ? error.message : 'Could not sign out other devices', 'error'); } finally { setBusy(false); } };
  return <main style={{ padding: mobile ? '14px 12px 42px' : '18px 22px 48px', maxWidth: '100%' }}><div style={{ marginBottom: 15 }}><h2 style={{ margin: 0, color: T.TEXT, fontSize: 19 }}>Account security</h2><p style={{ margin: '5px 0 0', color: T.TEXT_SECONDARY, fontSize: 13 }}>Manage password recovery and the devices that can access this seller workspace.</p></div><section style={{ ...CARD, padding: 17, marginBottom: 13 }}><b style={{ color: T.TEXT, fontSize: 14 }}>Password</b><p style={{ margin: '5px 0 13px', color: T.TEXT_SECONDARY, fontSize: 12.5 }}>For security, password changes use a time-limited link sent to {me?.email || 'your sign-in email'}.</p><Button primary disabled={busy || !me?.email} onClick={reset}>Send reset link</Button></section><section style={{ ...CARD, overflow: 'hidden' }}><div style={{ padding: '14px 16px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, borderBottom: `1px solid ${T.DIVIDER}` }}><div><b style={{ color: T.TEXT, fontSize: 14 }}>Signed-in devices</b><span style={{ display: 'block', color: T.TEXT_MUTED, fontSize: 12, marginTop: 3 }}>Review active browser sessions and remove other devices.</span></div><Button disabled={busy || sessions.length < 2} onClick={revokeOthers}>Sign out others</Button></div>{sessions.length ? sessions.map(session => <div key={session.id} style={{ padding: '13px 16px', borderBottom: `1px solid ${T.DIVIDER}` }}><b style={{ color: T.TEXT_LABEL, fontSize: 13 }}>{session.current ? 'This device' : session.user_agent || 'Browser session'}</b><small style={{ display: 'block', color: T.TEXT_MUTED, marginTop: 4 }}>Last active {new Date(session.last_seen_at).toLocaleString('en-IN')}{session.ip_address ? ` · ${session.ip_address}` : ''}</small></div>) : <div style={{ padding: 24, color: T.TEXT_MUTED, fontSize: 13 }}>Loading active sessions…</div>}</section></main>;
}
