'use client';

import { useCallback, useEffect, useState } from 'react';
import { apiFetch, adminApi } from '@/lib/api';
import { useAppState } from '@/lib/AppStateContext';
import * as T from '@/lib/theme';
const CARD={background:'linear-gradient(165deg,var(--nx-glass-1),var(--nx-glass-2))',border:'1px solid var(--nx-glass-border)',borderRadius:14,boxShadow:'0 12px 30px rgba(15,31,61,.07)'};
const field={width:'100%',height:40,boxSizing:'border-box',borderRadius:8,border:`1px solid ${T.INPUT_BORDER}`,background:T.SURFACE,color:T.TEXT,padding:'0 11px',fontSize:13};
const title=v=>(v||'').replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase());
function Button({children,onClick,primary=false,disabled=false}){return <button disabled={disabled} onClick={onClick} style={{height:34,padding:'0 11px',borderRadius:8,border:`1px solid ${primary?T.NAVY:T.INPUT_BORDER}`,background:primary?T.NAVY:T.SURFACE,color:primary?'#fff':T.TEXT,fontWeight:720,fontSize:12,cursor:disabled?'wait':'pointer',opacity:disabled?.6:1}}>{children}</button>}
const CONFIG={
 'courier-rules':['Courier rules','Set operational defaults for how orders are offered to eligible couriers.',[['autoAllocate','Enable smart courier allocation','boolean'],['preferLowestRate','Prefer lowest configured rate','boolean'],['maxDeliveryDays','Maximum delivery promise (days)','number']]],
 label:['Label settings','Store label and return-document preferences used by your fulfillment team.',[['labelSize','Label size','select:4×6|4×4|A4'],['includeInvoice','Include invoice with label','boolean'],['includeReturnLabel','Create return label by default','boolean']]],
 printer:['Printer settings','Save the workstation printing defaults for operations.',[['printerName','Printer name','text'],['copies','Default copies','number'],['autoPrint','Print labels after generation','boolean']]],
 'inv-settings':['Invoice settings','Configure the operational invoice defaults for your workspace.',[['prefix','Invoice prefix','text'],['gstRate','GST rate (%)','number'],['showHsn','Show HSN details','boolean']]],
 notifications:['Order notifications','Choose which internal operational updates your team receives.',[['orderCreated','New order alerts','boolean'],['ndrOpened','NDR alerts','boolean'],['shipmentDelivered','Delivery alerts','boolean']]],
 'account-config':['Account configuration','Save workspace-level preferences without affecting carrier credentials.',[['companyName','Company display name','text'],['defaultWeight','Default parcel weight (g)','number'],['weekStartsMonday','Week starts Monday','boolean']]],
};
function Settings({activeId,mobile}){const c=CONFIG[activeId];const {showToast}=useAppState();const [values,setValues]=useState({});const [busy,setBusy]=useState(false);const load=useCallback(()=>apiFetch(`/v1/settings/${activeId}`).then(x=>setValues(x.values||{})).catch(()=>setValues({})),[activeId]);useEffect(()=>{load()},[load]);const save=async()=>{setBusy(true);try{await apiFetch(`/v1/settings/${activeId}`,{method:'PUT',body:values});showToast('Settings saved to your workspace');}catch(e){showToast(e.message||'Settings could not be saved','error')}finally{setBusy(false)}};return <main style={{padding:mobile?'14px 12px 42px':'18px 22px 48px',maxWidth:900}}><div style={{marginBottom:15}}><h2 style={{margin:0,color:T.TEXT,fontSize:19}}>{c[0]}</h2><p style={{margin:'5px 0 0',color:T.TEXT_SECONDARY,fontSize:13}}>{c[1]}</p></div><section style={{...CARD,padding:17,display:'grid',gap:13}}>{c[2].map(([key,label,kind])=><label key={key} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:18,color:T.TEXT_LABEL,fontSize:13,fontWeight:650}}><span>{label}</span>{kind==='boolean'?<input aria-label={label} type="checkbox" checked={Boolean(values[key])} onChange={e=>setValues({...values,[key]:e.target.checked})} style={{width:18,height:18,accentColor:T.ACCENT}} />:kind.startsWith('select:')?<select value={values[key]||kind.split(':')[1].split('|')[0]} onChange={e=>setValues({...values,[key]:e.target.value})} style={{...field,width:170}}>{kind.split(':')[1].split('|').map(x=><option key={x}>{x}</option>)}</select>:<input aria-label={label} type={kind} value={values[key]??''} onChange={e=>setValues({...values,[key]:kind==='number'?Number(e.target.value):e.target.value})} style={{...field,width:190}}/>}</label>)}<div><Button primary disabled={busy} onClick={save}>{busy?'Saving…':'Save changes'}</Button></div></section></main>}
function Reports({activeId,mobile}){const [data,setData]=useState(null);useEffect(()=>{apiFetch('/v1/reports/summary').then(setData).catch(()=>setData({}))},[]);const cards=[['Orders',data?.orders],['Shipments',data?.shipments],['NDR cases',data?.ndr]];return <main style={{padding:mobile?'14px 12px 42px':'18px 22px 48px',maxWidth:1100}}><h2 style={{margin:0,color:T.TEXT,fontSize:19}}>{activeId==='weight'?'Weight discrepancies':'MIS report'}</h2><p style={{color:T.TEXT_SECONDARY,fontSize:13}}>Live operational totals from your workspace. Export integrations are added once a reporting destination is selected.</p><div style={{display:'grid',gridTemplateColumns:mobile?'1fr':'repeat(3,1fr)',gap:12}}>{cards.map(([name,rows])=><section key={name} style={{...CARD,padding:16}}><b style={{color:T.TEXT,fontSize:14}}>{name}</b><div style={{marginTop:12,display:'grid',gap:7}}>{rows?.length?rows.map(r=><div key={r.state} style={{display:'flex',justifyContent:'space-between',color:T.TEXT_SECONDARY,fontSize:13}}><span>{title(r.state)}</span><b style={{color:T.TEXT}}>{r.count}</b></div>):<span style={{color:T.TEXT_MUTED,fontSize:13}}>Loading live totals…</span>}</div></section>)}</div><section style={{...CARD,padding:16,marginTop:12,color:T.TEXT_SECONDARY,fontSize:13}}>Recorded shipping spend: <b style={{color:T.TEXT}}>₹{((data?.shippingSpendPaise||0)/100).toLocaleString('en-IN')}</b></section></main>}
function Tickets({admin,mobile}){const {showToast}=useAppState();const [items,setItems]=useState([]);const [f,setF]=useState({subject:'',category:'Operations',message:'',priority:'normal'});const load=useCallback(()=>admin?adminApi.auditEvents().then(()=>apiFetch('/v1/admin/tickets')).then(x=>setItems(x.items||[])):apiFetch('/v1/tickets').then(x=>setItems(x.items||[])),[admin]);useEffect(()=>{load().catch(()=>setItems([]))},[load]);const create=async()=>{try{await apiFetch('/v1/tickets',{method:'POST',body:f});setF({subject:'',category:'Operations',message:'',priority:'normal'});showToast('Support ticket created');load()}catch(e){showToast(e.message||'Ticket could not be created','error')}};const update=async(r,state)=>{try{await apiFetch(`/v1/admin/tickets/${r.id}`,{method:'PATCH',body:{state,resolutionNote:state==='resolved'?'Resolved from admin operations':'In review'}});showToast('Ticket updated');load()}catch(e){showToast(e.message||'Ticket could not be updated','error')}};return <main style={{padding:mobile?'14px 12px 42px':'18px 22px 48px',maxWidth:1100}}><h2 style={{margin:0,color:T.TEXT,fontSize:19}}>{admin?'Support centre':'Support tickets'}</h2><p style={{color:T.TEXT_SECONDARY,fontSize:13}}>{admin?'Manage seller operational requests from one queue.':'Create and track operational requests for the platform team.'}</p>{!admin&&<section style={{...CARD,padding:16,display:'grid',gap:9,marginBottom:13}}><input placeholder="What do you need help with?" value={f.subject} onChange={e=>setF({...f,subject:e.target.value})} style={field}/><div style={{display:'grid',gridTemplateColumns:'1fr 140px',gap:9}}><input placeholder="Category" value={f.category} onChange={e=>setF({...f,category:e.target.value})} style={field}/><select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})} style={field}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></div><textarea placeholder="Describe the issue" value={f.message} onChange={e=>setF({...f,message:e.target.value})} style={{...field,height:90,padding:'10px 11px',resize:'vertical'}}/><div><Button primary disabled={!f.subject||!f.message} onClick={create}>Create ticket</Button></div></section>}<section style={{...CARD,overflow:'hidden'}}>{items.length?items.map(r=><div key={r.id} style={{padding:14,borderBottom:`1px solid ${T.DIVIDER}`,display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><b style={{color:T.TEXT,fontSize:13}}>{r.subject}</b><small style={{display:'block',color:T.TEXT_MUTED,marginTop:4}}>{r.seller_name?`${r.seller_name} · `:''}{title(r.category)} · {title(r.priority)} · {title(r.state)}</small></div>{admin&&r.state!=='resolved'&&<Button primary onClick={()=>update(r,'resolved')}>Resolve</Button>}</div>):<div style={{padding:24,color:T.TEXT_SECONDARY,fontSize:13}}>No tickets yet.</div>}</section></main>}
export default function LiveWorkspaceTools({activeId,mobile}){if(CONFIG[activeId])return <Settings activeId={activeId} mobile={mobile}/>;if(['mis','weight'].includes(activeId))return <Reports activeId={activeId} mobile={mobile}/>;if(activeId==='a-tickets')return <Tickets admin mobile={mobile}/>;return <Tickets mobile={mobile}/>}
