'use client';

import { useCallback, useEffect, useState } from 'react';
import { apiFetch, ApiError } from '@/lib/api';
import { useAppState } from '@/lib/AppStateContext';
import * as T from '@/lib/theme';

const CARD = { background: 'var(--nx-surface)', border: '1px solid var(--nx-border)', borderRadius: 10, boxShadow: '0 1px 2px rgba(20,44,66,.04), 0 8px 24px rgba(20,44,66,.045)' };
const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Number(value || 0) / 100);
const title = value => String(value || '').replaceAll('_', ' ').replace(/\b\w/g, c => c.toUpperCase());
function Button({ children, onClick, primary, disabled }) { return <button disabled={disabled} onClick={onClick} style={{ height: 35, padding: '0 11px', borderRadius: 8, border: `1px solid ${primary ? T.NAVY : T.INPUT_BORDER}`, background: primary ? T.NAVY : T.SURFACE, color: primary ? '#fff' : T.TEXT, fontSize: 12, fontWeight: 720, cursor: disabled ? 'wait' : 'pointer', opacity: disabled ? .58 : 1 }}>{children}</button>; }

export default function LiveShipmentDetail({ mobile }) {
  const { showToast, nav } = useAppState(); const [shipment, setShipment] = useState(null); const [events, setEvents] = useState([]); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const list = await apiFetch('/v1/shipments'); const first = list.items?.[0]; if (!first) return setShipment(false); const [detail, tracking] = await Promise.all([apiFetch(`/v1/shipments/${first.id}`), apiFetch(`/v1/shipments/${first.id}/tracking`)]); setShipment({ ...first, ...detail }); setEvents(tracking.items || detail.events || []); } catch { setShipment(false); } }, []);
  useEffect(() => { load(); }, [load]); // eslint-disable-line react-hooks/set-state-in-effect -- async fetch on mount; state is set after the await
  // Label PDFs need object storage, which is not connected yet.
  const createLabel = () => showToast('Label generation is coming soon. It needs file storage, which is not connected yet.');
  if (shipment === null) return <main style={{ padding: mobile ? '14px 12px 42px' : '18px 22px 48px', color: T.TEXT_SECONDARY, fontSize: 13 }}>Loading shipment detail…</main>;
  if (!shipment) return <main style={{ padding: mobile ? '14px 12px 42px' : '18px 22px 48px', maxWidth: 880 }}><section style={{ ...CARD, padding: 34, textAlign: 'center' }}><b style={{ color: T.TEXT, fontSize: 16 }}>No booked shipment yet</b><p style={{ color: T.TEXT_SECONDARY, fontSize: 13 }}>Create an order, compare rates, and book a courier to see its live tracking detail here.</p><Button primary onClick={() => nav('orders')}>Open orders</Button></section></main>;
  const statusColor = shipment.state === 'delivered' ? T.GREEN : shipment.state === 'ndr' || shipment.state === 'rto' ? T.AMBER : T.ACCENT;
  return <main style={{ padding: mobile ? '14px 12px 42px' : '18px 22px 48px', maxWidth: 1040 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 14, flexWrap: 'wrap', marginBottom: 15 }}><div><h2 style={{ margin: 0, color: T.TEXT, fontSize: 19 }}>Shipment detail</h2><p style={{ margin: '5px 0 0', color: T.TEXT_SECONDARY, fontSize: 13 }}>Live operational record for this booked shipment.</p></div><div style={{ display: 'flex', gap: 8 }}><Button onClick={load}>Refresh</Button><Button primary disabled={busy} onClick={createLabel}>{busy ? 'Queueing…' : 'Generate label'}</Button></div></div><section style={{ ...CARD, padding: 18, display: 'grid', gridTemplateColumns: mobile ? '1fr' : '1.3fr repeat(3,minmax(0,1fr))', gap: 16, marginBottom: 13 }}><div><span style={{ color: T.TEXT_MUTED, fontSize: 11.5, fontWeight: 800, letterSpacing: '.08em', textTransform: 'uppercase' }}>AWB</span><b style={{ display: 'block', color: T.TEXT, fontFamily: T.MONO, fontSize: 17, marginTop: 7 }}>{shipment.awb}</b><span style={{ display: 'inline-flex', marginTop: 9, padding: '4px 8px', borderRadius: 99, color: statusColor, background: `${statusColor}14`, fontSize: 11.5, fontWeight: 750 }}>{title(shipment.state)}</span></div>{[['Order', shipment.order_number], ['Courier', shipment.courier_name || 'Configured carrier'], ['Shipping charge', money(shipment.shipping_charge_paise)]].map(([label, value]) => <div key={label}><span style={{ color: T.TEXT_MUTED, fontSize: 11.5, fontWeight: 800, letterSpacing: '.08em', textTransform: 'uppercase' }}>{label}</span><b style={{ display: 'block', color: T.TEXT_LABEL, fontSize: 14, marginTop: 8 }}>{value}</b></div>)}</section><section style={{ ...CARD, overflow: 'hidden' }}><div style={{ padding: '14px 16px', color: T.TEXT, fontSize: 14, fontWeight: 760, borderBottom: `1px solid ${T.DIVIDER}` }}>Tracking timeline</div>{events.length ? events.map((event, index) => <div key={`${event.occurred_at}-${index}`} style={{ display: 'grid', gridTemplateColumns: '18px 1fr auto', gap: 11, alignItems: 'start', padding: '14px 16px', borderBottom: `1px solid ${T.DIVIDER}` }}><span style={{ width: 10, height: 10, marginTop: 4, borderRadius: 99, background: index === 0 ? statusColor : T.BORDER, boxShadow: index === 0 ? `0 0 0 4px ${statusColor}14` : 'none' }} /><span><b style={{ display: 'block', color: T.TEXT_LABEL, fontSize: 13 }}>{event.description || title(event.state)}</b><small style={{ display: 'block', color: T.TEXT_MUTED, marginTop: 4 }}>{event.location || 'Courier network'} · {title(event.source || 'tracking')}</small></span><small style={{ color: T.TEXT_MUTED, fontSize: 11.5, whiteSpace: 'nowrap' }}>{new Date(event.occurred_at).toLocaleString('en-IN')}</small></div>) : <div style={{ padding: 24, color: T.TEXT_MUTED, fontSize: 13 }}>The courier has not posted a tracking event yet.</div>}</section></main>;
}
