'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { adminApi, ApiError } from '@/lib/api';
import { useAppState } from '@/lib/AppStateContext';
import * as T from '@/lib/theme';

const CARD = { background: 'linear-gradient(165deg,var(--nx-glass-1),var(--nx-glass-2))', border: '1px solid var(--nx-glass-border)', borderRadius: 14, boxShadow: '0 12px 30px rgba(15,31,61,.07)' };
const title = (v = '') => v.replaceAll('_', ' ').replace(/\b\w/g, c => c.toUpperCase());
const money = (v = 0) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Number(v) / 100);
function Button({ children, onClick, disabled, primary = false }) { return <button onClick={onClick} disabled={disabled} style={{ height: 33, padding: '0 10px', borderRadius: 8, border: `1px solid ${primary ? T.NAVY : T.INPUT_BORDER}`, color: primary ? '#fff' : T.TEXT, background: primary ? T.NAVY : T.SURFACE, fontSize: 12, fontWeight: 720, cursor: disabled ? 'wait' : 'pointer', opacity: disabled ? .6 : 1 }}>{children}</button>; }
function Pill({ children, tone = 'ok' }) { const c = tone === 'warn' ? T.AMBER : tone === 'bad' ? T.RED : T.GREEN; return <span style={{ display: 'inline-flex', padding: '4px 8px', borderRadius: 99, color: c, background: `${c}14`, fontWeight: 720, fontSize: 11.5 }}>{children}</span>; }

export default function LiveAdminOperations({ activeId, mobile }) {
  const { showToast } = useAppState(); const [items, setItems] = useState(null); const [busy, setBusy] = useState('');
  const config = useMemo(() => ({
    'a-kyc': { title: 'KYC verification', intro: 'Review submitted seller identities and settlement details.', load: () => adminApi.kycQueue('pending_review'), columns: ['Seller', 'Business identity', 'Settlement', 'Submitted', ''], cells: r => [<><b>{r.seller_name}</b><small>{r.entity_type}</small></>, <><b>{r.gstin}</b><small>{r.pan}</small></>, <><b>{r.bank_account_holder}</b><small>{r.bank_ifsc}</small></>, new Date(r.submitted_at).toLocaleString('en-IN'), <div style={{ display: 'flex', gap: 6 }}><Button primary disabled={busy === r.seller_id} onClick={() => decide(r, 'verified')}>Approve</Button><Button disabled={busy === r.seller_id} onClick={() => decide(r, 'rejected')}>Reject</Button></div>] },
    'a-cod': { title: 'COD settlements', intro: 'Review and release COD remittance cycles created from delivered shipments.', load: () => adminApi.codRemittances(), columns: ['Seller', 'Cycle', 'Shipments', 'Net remittance', 'Status', ''], cells: r => [<b>{r.seller_name}</b>, `${r.cycle_start} → ${r.cycle_end}`, r.shipment_count, money(r.net_remitted_paise), <Pill tone={r.status === 'remitted' ? 'ok' : 'warn'}>{title(r.status)}</Pill>, r.status === 'pending' ? <Button primary disabled={busy === r.id} onClick={() => cod(r, 'approve')}>Approve</Button> : r.status === 'approved' ? <Button primary disabled={busy === r.id} onClick={() => cod(r, 'remit')}>Mark remitted</Button> : null] },
    'a-invoices': { title: 'Invoices', intro: 'Issue seller shipping invoices and queue the document generation flow.', load: () => adminApi.invoices(), columns: ['Invoice', 'Seller', 'Period', 'Total', 'Status', ''], cells: r => [<b>{r.invoice_number}</b>, r.seller_name, `${r.period_start} → ${r.period_end}`, money(r.total_paise), <Pill tone={r.status === 'issued' ? 'ok' : 'warn'}>{title(r.status)}</Pill>, r.status === 'draft' ? <Button primary disabled={busy === r.id} onClick={() => issue(r)}>Issue</Button> : null] },
    'a-jobs': { title: 'Background jobs', intro: 'Live operational jobs queued by channel sync, documents, and integrations.', load: () => adminApi.jobs(), columns: ['Job', 'Seller', 'State', 'Attempts', 'Queued', ''], cells: r => [<b>{title(r.job_type)}</b>, r.seller_name || 'Platform', <Pill tone={r.state === 'failed' ? 'bad' : r.state === 'queued' ? 'warn' : 'ok'}>{title(r.state)}</Pill>, r.attempts, new Date(r.queued_at).toLocaleString('en-IN'), r.state === 'failed' ? <Button primary disabled={busy === r.id} onClick={() => retry(r)}>Retry</Button> : null] },
    'a-audit': { title: 'Audit trail', intro: 'Immutable administrative activity across sellers, couriers, finance, and access.', load: () => adminApi.auditEvents(), columns: ['When', 'Actor', 'Action', 'Target', 'Workspace'], cells: r => [new Date(r.created_at).toLocaleString('en-IN'), r.actor_name || 'System', <b>{title(r.action)}</b>, `${r.target_type || '—'} ${r.target_id ? String(r.target_id).slice(0, 8) : ''}`, r.seller_name || 'Platform'] },
  })[activeId], [activeId, busy]);
  const load = useCallback(async () => { if (!config) return; try { const x = await config.load(); setItems(x.items || []); } catch { setItems([]); } }, [config]);
  useEffect(() => { load(); }, [load]);
  const decide = async (r, decision) => { setBusy(r.seller_id); try { await adminApi.kycDecision(r.seller_id, decision, decision === 'rejected' ? 'Please review submitted business documents.' : undefined); showToast(`KYC ${decision}`); load(); } catch (e) { showToast(e instanceof ApiError ? e.message : 'KYC action failed', 'error'); } finally { setBusy(''); } };
  const cod = async (r, action) => { setBusy(r.id); try { await apiCall(`/v1/admin/cod-remittances/${r.id}/${action}`, action === 'remit' ? { bankReference: `NX-DEMO-${Date.now()}` } : {}); showToast(action === 'approve' ? 'COD cycle approved' : 'COD cycle marked remitted'); load(); } catch (e) { showToast(e.message || 'COD action failed', 'error'); } finally { setBusy(''); } };
  const issue = async r => { setBusy(r.id); try { await apiCall(`/v1/admin/invoices/${r.id}/issue`); showToast('Invoice issued and document job queued'); load(); } catch (e) { showToast(e.message || 'Invoice could not be issued', 'error'); } finally { setBusy(''); } };
  const retry = async r => { setBusy(r.id); try { await adminApi.retryJob(r.id); showToast('Job retry queued'); load(); } catch (e) { showToast(e.message || 'Retry failed', 'error'); } finally { setBusy(''); } };
  if (!config) return null;
  return <div style={{ padding: mobile ? '14px 12px 42px' : '18px 22px 48px', maxWidth: 1320 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'end', gap: 12, marginBottom: 15 }}><div><div style={{ color: T.TEXT, fontWeight: 760, fontSize: 19 }}>{config.title}</div><div style={{ color: T.TEXT_SECONDARY, marginTop: 4, fontSize: 13 }}>{config.intro}</div></div><Button onClick={load}>Refresh</Button></div>{items === null ? <div style={{ ...CARD, padding: 30, color: T.TEXT_SECONDARY }}>Loading operations…</div> : !items.length ? <div style={{ ...CARD, padding: 30, color: T.TEXT_SECONDARY }}>No records need attention right now.</div> : <div style={{ ...CARD, overflow: 'hidden' }}><div style={{ overflowX: 'auto' }}><table style={{ width: '100%', minWidth: 850, borderCollapse: 'collapse' }}><thead><tr>{config.columns.map(x => <th key={x} style={{ padding: '11px 14px', textAlign: 'left', background: T.TABLE_HEAD, color: T.TEXT_MUTED, fontSize: 10.5, letterSpacing: '.07em', textTransform: 'uppercase' }}>{x}</th>)}</tr></thead><tbody>{items.map(r => <tr key={r.id || r.seller_id}>{config.cells(r).map((cell, i) => <td key={i} style={{ padding: '13px 14px', borderTop: `1px solid ${T.DIVIDER}`, color: T.TEXT_LABEL, fontSize: 13 }}>{typeof cell === 'string' || typeof cell === 'number' ? cell : cell}</td>)}</tr>)}</tbody></table></div></div>}</div>;
}

async function apiCall(path, body = {}) { const { apiFetch } = await import('@/lib/api'); return apiFetch(path, { method: 'POST', body }); }
