'use client';
import { useEffect, useState } from 'react';
import { apiFetch, ApiError } from '@/lib/api';
import { useAppState } from '@/lib/AppStateContext';
import * as T from '@/lib/theme';

const field = { width:'100%', height:42, boxSizing:'border-box', border:'1px solid var(--nx-input-border)', borderRadius:8, background:T.SURFACE, color:T.TEXT, padding:'0 11px', fontSize:14 };
const Card=({children})=><div style={{background:'linear-gradient(165deg,var(--nx-glass-1),var(--nx-glass-2))',backdropFilter:'blur(18px)',border:'1px solid var(--nx-glass-border)',borderRadius:14,padding:18}}>{children}</div>;
export default function LiveCreateOrder({mobile, flow = 'forward'}) {
 const {nav,showToast}=useAppState(); const [setup,setSetup]=useState(null); const [busy,setBusy]=useState(false); const [quotes,setQuotes]=useState([]);
 const [f,setF]=useState({orderNumber:`${flow === 'reverse' ? 'RET' : flow === 'dropship' ? 'DS' : flow === 'ship_now' ? 'NOW' : 'WEB'}-${Date.now().toString().slice(-6)}`,fullName:'',phone:'',email:'',address:'',city:'',state:'',pincode:'',sku:'',name:'',quantity:'1',price:'',weight:'500',paymentMode:'prepaid',cod:''});
 useEffect(()=>{Promise.all([apiFetch('/v1/warehouses'),apiFetch('/v1/products')]).then(([w,p])=>setSetup({warehouse:w.items?.[0],product:p.items?.[0]})).catch(()=>setSetup({}));},[]);
 useEffect(()=>{ if(!/^\d{6}$/.test(f.pincode)||!Number(f.weight)) return setQuotes([]); const timer=window.setTimeout(()=>apiFetch('/v1/shipping/quotes',{method:'POST',body:{destinationPincode:f.pincode,weightG:Number(f.weight),paymentMode:f.paymentMode}}).then(x=>setQuotes(x.quotes||[])).catch(()=>setQuotes([])),250); return()=>window.clearTimeout(timer); },[f.pincode,f.weight,f.paymentMode]);
 const set=(k)=>(e)=>setF({...f,[k]:e.target.value}); const product=setup?.product;
 const submit=async(e)=>{e.preventDefault();if(!setup?.warehouse)return showToast('Create a warehouse first in Settings.', 'error');setBusy(true);try{const unit=Math.round(Number(f.price||product?.unit_price_paise/100||0)*100);await apiFetch('/v1/orders',{method:'POST',body:{warehouseId:setup.warehouse.id,orderNumber:f.orderNumber,orderFlow:flow,paymentMode:f.paymentMode,codAmountPaise:f.paymentMode==='cod'?Math.round(Number(f.cod||f.price)*100):0,customer:{fullName:f.fullName,email:f.email||undefined,phone:f.phone,addressLine1:f.address,city:f.city,state:f.state,pincode:f.pincode},items:[{productId:product?.id,sku:f.sku||product?.sku||'CUSTOM',name:f.name||product?.name||'Custom item',quantity:Number(f.quantity),unitPricePaise:unit,weightG:Number(f.weight)}]}});showToast('Order created and added to operations.');nav('orders');}catch(x){showToast(x instanceof ApiError?x.message:'Unable to create order','error');}finally{setBusy(false)}};
 const orderFields=[['Order number','orderNumber'],['Customer name','fullName'],['Phone','phone'],['Email','email'],['Address','address'],['City','city'],['State','state'],['Pincode','pincode']];
 const productFields=[['SKU','sku'],['Product name','name'],['Quantity','quantity'],['Unit price ₹','price'],['Weight (g)','weight'],['COD amount ₹','cod']];
 const renderFields=(fields)=><div style={{display:'grid',gridTemplateColumns:mobile?'1fr':'1fr 1fr',gap:13}}>{fields.map(([l,k])=><label key={k} style={{fontSize:12.5,fontWeight:650,color:T.TEXT_LABEL}}>{l}<input required={['orderNumber','fullName','phone','address','city','state','pincode','quantity','weight'].includes(k)} value={f[k]} onChange={set(k)} type={['quantity','price','weight','cod'].includes(k)?'number':k==='email'?'email':'text'} style={{...field,marginTop:6}} /></label>)}</div>;
 return <form onSubmit={submit} style={{padding:mobile?'14px 12px 42px':'18px 22px 48px',maxWidth:980}}><div style={{fontSize:18,fontWeight:760,color:T.TEXT}}>{flow === 'reverse' ? 'Create reverse pickup' : flow === 'dropship' ? 'Create dropship order' : flow === 'ship_now' ? 'Ship now' : 'Create a live order'}</div><p style={{color:T.TEXT_SECONDARY,fontSize:13.5,margin:'6px 0 16px'}}>This writes directly to your workspace and becomes visible in the admin queue.</p><div style={{display:'grid',gap:14}}><Card><div style={{marginBottom:15}}><b style={{color:T.TEXT,fontSize:15}}>Order & customer details</b><span style={{display:'block',marginTop:4,color:T.TEXT_MUTED,fontSize:12.5}}>Who is receiving this shipment and where it needs to go.</span></div>{renderFields(orderFields)}</Card><Card><div style={{marginBottom:15}}><b style={{color:T.TEXT,fontSize:15}}>Product & shipment details</b><span style={{display:'block',marginTop:4,color:T.TEXT_MUTED,fontSize:12.5}}>Add the parcel contents, value, weight, and payment mode.</span></div>{renderFields(productFields)}<label style={{display:'block',maxWidth:mobile?'none':'calc(50% - 7px)',marginTop:13,fontSize:12.5,fontWeight:650,color:T.TEXT_LABEL}}>Payment mode<select value={f.paymentMode} onChange={set('paymentMode')} style={{...field,marginTop:6}}><option value="prepaid">Prepaid</option><option value="cod">Cash on delivery</option></select></label></Card>{quotes.length>0&&<Card><b style={{fontSize:13,color:T.TEXT}}>Live courier rates configured by platform admin</b><div style={{display:'grid',gridTemplateColumns:mobile?'1fr':'repeat(3,1fr)',gap:9,marginTop:10}}>{quotes.map((q,i)=><div key={q.provider.code} style={{padding:12,border:`1px solid ${i===0?T.ACCENT:T.BORDER}`,borderRadius:10,background:i===0?'rgba(0,179,164,.08)':T.SURFACE}}><b style={{display:'block',fontSize:13,color:T.TEXT}}>{q.provider.name}</b><span style={{display:'block',fontSize:12,color:T.TEXT_MUTED,marginTop:3}}>{q.service.name}</span><strong style={{display:'block',marginTop:8,color:T.TEXT,fontSize:18}}>₹{q.price.total.toFixed(2)}</strong></div>)}</div></Card>}<div><button disabled={busy} type="submit" style={{height:42,padding:'0 16px',border:0,borderRadius:8,background:T.NAVY,color:'#fff',fontWeight:700,cursor:'pointer'}}>{busy?'Creating…':flow === 'reverse'?'Create reverse pickup':'Create order'}</button></div></div></form>;
}
