'use client';
import { useEffect, useState } from 'react';
import { apiFetch, ApiError } from '@/lib/api';
import { useAppState } from '@/lib/AppStateContext';
import * as T from '@/lib/theme';

const field = { width:'100%', height:42, boxSizing:'border-box', border:'1px solid var(--nx-input-border)', borderRadius:8, background:T.SURFACE, color:T.TEXT, padding:'0 11px', fontSize:14 };
const Card=({children})=><div style={{background:'linear-gradient(165deg,var(--nx-glass-1),var(--nx-glass-2))',backdropFilter:'blur(18px)',border:'1px solid var(--nx-glass-border)',borderRadius:14,padding:18}}>{children}</div>;
export default function LiveCreateOrder({mobile}) {
 const {nav,showToast}=useAppState(); const [setup,setSetup]=useState(null); const [busy,setBusy]=useState(false);
 const [f,setF]=useState({orderNumber:`WEB-${Date.now().toString().slice(-6)}`,fullName:'',phone:'',email:'',address:'',city:'',state:'',pincode:'',sku:'',name:'',quantity:'1',price:'',weight:'500',paymentMode:'prepaid',cod:''});
 useEffect(()=>{Promise.all([apiFetch('/v1/warehouses'),apiFetch('/v1/products')]).then(([w,p])=>setSetup({warehouse:w.items?.[0],product:p.items?.[0]})).catch(()=>setSetup({}));},[]);
 const set=(k)=>(e)=>setF({...f,[k]:e.target.value}); const product=setup?.product;
 const submit=async(e)=>{e.preventDefault();if(!setup?.warehouse)return showToast('Create a warehouse first in Settings.', 'error');setBusy(true);try{const unit=Math.round(Number(f.price||product?.unit_price_paise/100||0)*100);await apiFetch('/v1/orders',{method:'POST',body:{warehouseId:setup.warehouse.id,orderNumber:f.orderNumber,paymentMode:f.paymentMode,codAmountPaise:f.paymentMode==='cod'?Math.round(Number(f.cod||f.price)*100):0,customer:{fullName:f.fullName,email:f.email||undefined,phone:f.phone,addressLine1:f.address,city:f.city,state:f.state,pincode:f.pincode},items:[{productId:product?.id,sku:f.sku||product?.sku||'CUSTOM',name:f.name||product?.name||'Custom item',quantity:Number(f.quantity),unitPricePaise:unit,weightG:Number(f.weight)}]}});showToast('Order created and added to operations.');nav('orders');}catch(x){showToast(x instanceof ApiError?x.message:'Unable to create order','error');}finally{setBusy(false)}};
 const labels=[['Order number','orderNumber'],['Customer name','fullName'],['Phone','phone'],['Email','email'],['Address','address'],['City','city'],['State','state'],['Pincode','pincode'],['SKU','sku'],['Product name','name'],['Quantity','quantity'],['Unit price ₹','price'],['Weight (g)','weight'],['COD amount ₹','cod']];
 return <form onSubmit={submit} style={{padding:mobile?'14px 12px 42px':'18px 22px 48px',maxWidth:980}}><Card><div style={{fontSize:18,fontWeight:760,color:T.TEXT}}>Create a live order</div><p style={{color:T.TEXT_SECONDARY,fontSize:13.5}}>This writes directly to your workspace and becomes visible in the admin queue.</p><div style={{display:'grid',gridTemplateColumns:mobile?'1fr':'1fr 1fr',gap:13}}>{labels.map(([l,k])=><label key={k} style={{fontSize:12.5,fontWeight:650,color:T.TEXT_LABEL}}>{l}<input required={['orderNumber','fullName','phone','address','city','state','pincode','quantity','weight'].includes(k)} value={f[k]} onChange={set(k)} type={['quantity','price','weight','cod'].includes(k)?'number':k==='email'?'email':'text'} style={{...field,marginTop:6}} /></label>)}<label style={{fontSize:12.5,fontWeight:650,color:T.TEXT_LABEL}}>Payment mode<select value={f.paymentMode} onChange={set('paymentMode')} style={{...field,marginTop:6}}><option value="prepaid">Prepaid</option><option value="cod">Cash on delivery</option></select></label></div><button disabled={busy} type="submit" style={{marginTop:18,height:42,padding:'0 16px',border:0,borderRadius:8,background:T.NAVY,color:'#fff',fontWeight:700,cursor:'pointer'}}>{busy?'Creating…':'Create order'}</button></Card></form>;
}
